# Generated by Django 4.2.4 on 2023-08-20 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='age',
            field=models.CharField(default=datetime.datetime(2023, 8, 20, 5, 39, 45, 105390, tzinfo=datetime.timezone.utc), max_length=3),
            preserve_default=False,
        ),
    ]
