# Generated by Django 4.2.4 on 2023-08-20 08:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_candidate_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
    ]
