# Generated by Django 4.2.4 on 2023-08-20 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_candidate_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='job',
            field=models.CharField(default=datetime.datetime(2023, 8, 20, 9, 6, 58, 512389, tzinfo=datetime.timezone.utc), max_length=5),
            preserve_default=False,
        ),
    ]
